Some commits
NullCGT/SpliceHack-Rewrite pull request #17
Opened 2021-08-25 05:08 UTC by RojjaCebolla

Feel free to git cherry-pick anything you like from this branch, just gonna be some small tweaks that might fit into your combat changes.

2021-08-25 08:09 UTC, RojjaCebolla commented
https://user-images.githubusercontent.com/62170514/130752720-c86a4450-9b51-440d-91be-41f599ef16fb.mp4


https://user-images.githubusercontent.com/62170514/130752762-9b6ebfec-3201-4839-a2d0-ef14c36e729d.mp4

2021-08-25 15:04 UTC, RojjaCebolla commented
Originally, i was wanting to buff gauntlets of dex more - i wanted them to apply a bonus equal to their enchantment to nonmelee actions.  But then I realized that Dex already gives a substantial bonus to attack! (you call it to-hit :P)  I guess it's just never needed or impactful because hitting is not generally hard in vinalla. So, I'm not buffing the gloves yet, cuz maybe after your combat changes, those accuracy bonuses will be appealing.

Though, I do wanna make high Dex improve your hit chance with wands, as a zesty little side-bonus-incentive that can help gloves of dex matter more.  But AFAIK, Dex already applies to thrown objects (including potions!), missile attacks, and spells. Not sure whether it applies to melee whacks with potions, or to frost/fire horns. But it probably does and probably should!

Also: TIL that, unintuitively, Dwarves have higher Dex than Elves?!

2021-08-25 15:06 UTC, RojjaCebolla commented
for some reason those awful-garbage headers at the beginning of each source file have tabs in them. So for whitespace, I've been doing
`5dd :retab P`

2021-08-28 14:57 UTC, NullCGT requested changes

2021-08-28 14:57 UTC, NullCGT commented on src/uhitm.c
> +        tmp += uarmg->spe;
Needs to change to this:

`if (uarmg) tmp += uarmg->spe;`

If we don't check uarmg first, we'll segfault when barehanded since we're trying to access uninitialized memory.

2021-08-28 14:57 UTC, NullCGT commented on src/zap.c
> +        chance -= (ACURR(A_DEX) - 17);
Shouldn't this be `+=` instead of `-=`?

2021-08-28 14:57 UTC, NullCGT commented on src/dokick.c
> +     */
GOOD DOCUMENTATION. HECK YEAH.

2021-08-28 14:57 UTC, NullCGT commented on src/dokick.c
> +            } else if (!rn2(3) && !(g.maploc->looted & S_LRING)) {
I'm a little confused what's happening here. What is this check doing?

2021-08-28 15:25 UTC, RojjaCebolla commented on src/dokick.c
> +            } else if (!rn2(3) && !(g.maploc->looted & S_LRING)) {
it might be completely unnecessary, but it's ensuring that you've gotten stuff out of the sink before destroying it.

maybe one just shouldn't wear kicking boots when kicking sinks unless you wanna kick it apart. ;) it's a classic nethack "whoops!" moment with non-game-ending consequences.

2021-08-28 15:27 UTC, RojjaCebolla commented on src/dokick.c
> +            } else if (!rn2(3) && !(g.maploc->looted & S_LRING)) {
it might be completely unnecessary, but it's ensuring that you've gotten stuff out of the sink before destroying it.

maybe one just shouldn't wear kicking boots when kicking sinks unless you wanna kick it apart. ;) it's a classic nethack "whoops!" moment with non-game-ending consequences.

2021-08-28 15:32 UTC, RojjaCebolla commented on src/zap.c
> +        chance -= (ACURR(A_DEX) - 17);
i thought not? chance is supposed to roll *under* ac ? then again AC is a backwards thing.

`return (3 - chance < ac + spell_bonus);`

2021-08-28 15:38 UTC, RojjaCebolla commented on src/dokick.c
> +            } else if (!rn2(3) && !(g.maploc->looted & S_LRING)) {
oh whoops, this is a different line. well. i don't *remember* changing this one. i'll un-change it!

2021-08-28 15:40 UTC, RojjaCebolla commented on src/dokick.c
> +            } else if (!rn2(3) && !(g.maploc->looted & S_LRING)) {
well, i still support the thing i *thought* you were saying, which is that magically kicking things should risk breaking them regardless of whether you've gotten value yet. so i'll amend this commit.

2021-08-29 03:01 UTC, NullCGT approved these changes

2021-08-29 03:01 UTC, merged

2021-08-29 03:02 UTC, NullCGT commented
Merged! Probably should update the changelog